### ISSUE TITLE
DebugTools.h

### ISSUE THREAD

**Issue by cacolukiam** [Pedroalbuquerque/ESPBASE#10]
Hi
1st thank you so much for your amazing work!

I have a problem when compiling the sketch "example/WiFi_CFG_OTA_Telnet/WiFi_CFG_OTA_Telnet.ino" for my HUZZAH32. This message appears:
"fatal error: DebugTools.h: No such file or directory."
Do you know where I can find this required library?

Kind regards

**Comment by Pedroalbuquerque** [comment]
Hi cacolukiam,

sorry for taking a bot long to respond, this is a hobby so I do not see my messages as often as I would like.

I missed to publish this tools,
here they are https://github.com/Pedroalbuquerque/DebugTools 

enjoy,
Pedro Albuquerque

**Comment by Zodiac-69** [comment]
Hi Pedro
I do not see the "DebugTools" under your repository, am i missing something?

**Comment by cacolukiam** [comment]
The same here sorry :/

**Comment by Pedroalbuquerque** [comment]
sorry guys, it was private . New feature on github I was not aware yet.
I believe it is fixed (public).

can you try again ?

**Comment by Zodiac-69** [comment]
Hi Pedro
Thank you, i managed to download the file, i shall check it out as soon as i get time.
