### ISSUE TITLE
error: ECHO_PORT

### ISSUE THREAD

**Issue by luconezena** [Pedroalbuquerque/ESPBASE#11]
Thanks for your wonderful work.
In the compilation I get this error, where am I wrong?

Arduino:1.8.5 (Windows 10), Scheda:"NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

C:\Users\genov\Documents\Arduino\libraries\ESPBASE-master/ESPBASE.h: In member function 'void ESPBASE::WiFiconnect(uint8_t, int32_t, const uint8_t*)': 

C:\Users\genov\Documents\Arduino\libraries\ESPBASE-master/ESPBASE.h:183:2: error: 'ECHO_PORT' was not declared in this scope

  ECHO_PORT.println(WiFi.localIP());

  ^

C:\Users\genov\Documents\Arduino\libraries\ESPBASE-master/ESPBASE.h:208:3: error: 'ECHO_PORT' was not declared in this scope

   ECHO_PORT.println(WiFi.softAPIP());

**Comment by Pedroalbuquerque** [comment]
Hi Luconezena,

thanks for pointing out the issue.
In fact I missed to explain on the example the need to define ECHO_PORT and DEBUG_PORT.

so in your main file, you must add 

```
#define ECHO_PORT Serial
#define DEBUG_PORT Serial

```
before you 

`#include <ESPBASE.h>
`

in case you are using a wireless connection to the device you can even user Telnet to get your debug or echo messages. In this case you would use

```
#define ECHO_PORT Telnet
#define DEBUG_PORT Telnet

```

I am using platformio framework (both with ATOM or VSCode) that allow me to define this in the platformio.ini

```
[env:nodemcuv2]
platform=espressif8266
board=nodemcuv2
framework=arduino
lib_ignore = ESP32WebServer
;lib_deps = ${common.lib_deps}
lib_extra_dirs = ${common.lib_extra_dirs}
build_flags = ${common.build_flags} -DECHO_PORT=Serial -DDEBUG_PORT=Serial

upload_port=/dev/cu.wchusbserial1410
upload_speed=115200

```

let me know if this fixes your issue.

**Comment by Pedroalbuquerque** [comment]
considering the elapsed time I assume issue is solved with explanation provided, so closing the issue
