### ISSUE TITLE
 fatal error: DebugTools.h: No such file or directory  #include <DebugTools.h>

### ISSUE THREAD

**Issue by dc1rd** [Pedroalbuquerque/ESPBASE#13]
Hi, 

whEre can i get the file:
 fatal error: DebugTools.h: No such file or directory
 #include <DebugTools.h> ??

Arduino IDE 1.8.10

BR DC1RD

**Comment by Pedroalbuquerque** [comment]
Hi dc1rd,

you can find it here
[https://github.com/Pedroalbuquerque/DebugTools](https://github.com/Pedroalbuquerque/DebugTools)

hope this will help
