### ISSUE TITLE
Devicename is not used for hostname

### ISSUE THREAD

**Issue by stritti** [Pedroalbuquerque/ESPBASE#4]
If I configure the **"Name of Device"** within the **"General Settings"**, this name is not used for hostname within WiFi network. There is still the generic name `ESP8266-xxxx`.

How could that be changed?

**Comment by Pedroalbuquerque** [comment]
Hi Stritti,

Thank you for your comment, and in fact this is an unfinished work .

Actually the AP mode is entered when no connection is successful -in  <espbase.h>, and it load the default setting before entering AP mode.
>if ( !WIFI_connected or !CFG_saved){ // if no values saved or not good use defaults
>
>   // DEFAULT CONFIG
>  Serial.println("Setting AP mode default parameters");
>
>    //load config with default values
>    configLoadDefaults(getChipId());
>
>    WiFi.mode(WIFI_AP);
>    WiFi.softAP(config.ssid.c_str());
>    Serial.print("Wifi ip:");Serial.println(WiFi.softAPIP());
>   }

the default setting are define in <parameter.h>

>void configLoadDefaults(uint16_t ChipId){
>
>  #ifdef ARDUINO_ESP32_DEV
>    config.ssid = "ESP32-" + String(ChipId,HEX);       // SSID of access point
>  #elif ARDUINO_ESP8266_ESP01 || ARDUINO_ESP8266_NODEMCU
>    config.ssid = "ESP8266-" + String(ChipId,HEX);       // SSID of access point
>  #endif
>  config.password = "" ;   // password of access point

Hope this can help. Let me know if you succeeded.

Maybe you can even propose some code update to use the stored config value for device name, but bare in mind that one must be defined or the "default" one must be used.

**Comment by stritti** [comment]
Hi @Pedroalbuquerque 

thanks for your fast reply. I have already configured WiFi settings and the ESP is connected to the correct WiFi. But with the mentioned generic name, not with the given DeviceName. I Already tried to set 

``` 
   char __DeviceName[config.DeviceName.length()];
   config.DeviceName.toCharArray(__DeviceName, config.DeviceName.length());
   wifi_station_set_hostname(__DeviceName);

```

initial within setup(). But with no success.

**Comment by stritti** [comment]
After some searches I found, that mDNS may be required to solve this; https://tttapa.github.io/ESP8266/Chap10%20-%20Simple%20Web%20Server.html

https://tttapa.github.io/ESP8266/Chap08%20-%20mDNS.html

**Comment by Pedroalbuquerque** [comment]
thank you for the feedback, I actually did not used names (DNS) so far, and I would need to do some testing.
I will definitely play with that functionality as soon as I get a chance.
Good work!

**Comment by stritti** [comment]
okay I was able to test now.

I added to my template the include:
`#include <ESP8266mDNS.h>`

then I extended the `startup()`-method:

```
void setup() { 
  Serial.begin(115200);
  Esp.initialize();

  if (MDNS.begin(config.DeviceName.c_str())) {              // Start the mDNS responder for esp8266.local
    Serial.println("mDNS responder started");
    MDNS.addService("http", "tcp", 80); //for the OTA service
  } else {
    Serial.println("Error setting up MDNS responder!");
  }  
  
[...]
```

Sure, changing the value in the config (Website) will not affect directly. The ESP has to be rebooted then.

Reference: https://github.com/esp8266/Arduino/issues/458#issuecomment-142036792

**Comment by Pedroalbuquerque** [comment]
Hi Stritti

great job!

If you want to immediately apply the change you can modify the function in Page_General.h

```
void send_general_html()
{
	
	if (server.args() > 0 )  // Save Settings
	{	
		String temp = "";
		for ( uint8_t i = 0; i < server.args(); i++ ) {
			if (server.argName(i) == "devicename") config.DeviceName = urldecode(server.arg(i)); 
                        if (server.argName(i) == "OTApwd") config.OTApwd = urldecode(server.arg(i));
		}
		WriteConfig();
		firstStart = true;
```
[add this code] - same  used after saving network configurations

		//WiFirestart();
		ESP.restart();
		//ConfigureWifi();
```
	}
	server.send_P ( 200, "text/html", PAGE_AdminGeneralSettings ); 
	Serial.println(__FUNCTION__); 
	
	
}
```
