### ISSUE TITLE
Deprecated Ticker-ESP32

### ISSUE THREAD

**Issue by stritti** [Pedroalbuquerque/ESPBASE#5]
In Line https://github.com/Pedroalbuquerque/ESPBASE/blob/8ed47d61ee766be69682d861f53de6b7cf630af5/ESPBASE.h#L41

I think `Ticker-ESP32.h` could be replaced by `Ticker.h`

**Comment by Pedroalbuquerque** [comment]
Hi Stritti,

There are two reasons to have created ticker-esP32 lib:
1) this is a ESP8266 library, meaning it is part of hardware specific lib set , so not available to be included when we select a diferente board (like ESP32). It will result in error for not found file.

2) the ways interrupts are configured in ESP32 is different from ESP8266, so the hardware specific code must be different.

Yet I want that more higher level code to be the same , hence keeping the same function name.

Can you detail what you are proposing to improve to overcome this two issues ?

**Comment by stritti** [comment]
Hi Pedro,
I understand you, but
the lib is now integrated in the core. Have a look at: https://github.com/bertmelis/Ticker-esp32/blob/master/README.md

**Comment by Pedroalbuquerque** [comment]
Great news!! I will try it , thanks

**Comment by Pedroalbuquerque** [comment]
Replaced
