### ISSUE TITLE
Capital S for unix environments

### ISSUE THREAD

**Issue by stritti** [Pedroalbuquerque/ESPBASE#6]
To compile  on *inx there should be a capital `S` in `#include "Page_NTPSettings.h"`:

https://github.com/Pedroalbuquerque/ESPBASE/blob/8ed47d61ee766be69682d861f53de6b7cf630af5/ESPBASE.h#L76

and `#include "Page_NetworkConfiguration.h"` (instead of `PAGE`: 
https://github.com/Pedroalbuquerque/ESPBASE/blob/8ed47d61ee766be69682d861f53de6b7cf630af5/ESPBASE.h#L79

Required for example to run GitLAB-Build Pipeline using Platform.io.

**Comment by Pedroalbuquerque** [comment]
Thank you for the contribution Stritti
